<?xml version="1.0"?>
<package format="3">
  <name>bspline</name>
  <version>0.0.0</version>
  <description>The bspline package</description>

  <maintainer email="bzhouai@todo.todo">bzhouai</maintainer>
  <license>MIT</license>

  <!-- Build tool for ROS 2 -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Build and runtime dependencies -->
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>plan_env</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>

  <!-- Optional export tag for ament -->
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
